services:
  - type: web
    name: worldcup-2026-betting
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: python -m gunicorn app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
